[Icon Theme]
Name=GhostBSD
Comment=GhostBSD icons
Inherits=hicolor
Hidden=true
Directories=16x16/places,22x22/places,24x24/places,32x32/places,48x48/places,scalable/places

[16x16/places]
Size=16
Context=Places
Type=Fixed

[22x22/places]
Size=22
Context=Places
Type=Fixed

[24x24/places]
Size=24
Context=Places
Type=Fixed

[32x32/places]
Size=32
Context=Places
Type=Fixed

[48x48/places]
Size=48
Context=Places
Type=Fixed

[scalable/places]
Size=64
MinSize=16
MaxSize=512
Context=Places
Type=Scalable
